#!/bin/bash

echo Executing pre-commit hooks...

# source: http://stackoverflow.com/a/957978/836390
ROOT=$(git rev-parse --show-toplevel) || exit 1

if [ "$ROOT" == "" ]; then
	echo "`git rev-parse --show-toplevel` returned empty root path" >&2
	exit 1
fi

TMP=$(mktemp) || (echo commit aborted >&2; exit 1)
echo Running '`go fmt ./...`'
go fmt ./... || (rm $TMP; echo commit aborted >&2; exit 1)
echo Running '`go build ./...`'
go build ./... || (rm $TMP; echo commit aborted >&2; exit 1)