#!/bin/bash

echo Executing pre-commit hooks...

# source: http://stackoverflow.com/a/957978/836390
ROOT=$(git rev-parse --show-toplevel) || exit 1

if [ "$ROOT" == "" ]; then
	echo "`git rev-parse --show-toplevel` returned empty root path" >&2
	exit 1
fi

function die {
	if [ $# -eq 1 ]; then
		rm "$1"
	fi
	echo "commit aborted" >&1
	exit 1
}

# Try to write a temp file first so that we fail
# cleanly if we can't write to the local filesystem
# (the errors the go tool outputs are much more
# messy and verbose).
TMP=$(mktemp -t kudosXXX) || die
echo Running '`go fmt ./...`'
go fmt ./... || die "$TMP"
echo Running '`go -a build ./...`'
go build ./... || die "$TMP"
echo Running '`go build -a -tags dev ./...`'
go build -tags dev ./... || die "$TMP"
echo Running '`go build -a -tags debug ./...`'
go build -tags debug ./... || die "$TMP"
echo Running "\`go build -a -tags 'dev debug'./...\`"
go build -tags 'dev debug' ./... || die "$TMP"
rm "$TMP"
